language: node_js
before_install:
  - nvm install stable
  - node -v
  - npm -v
  - npm install -g gulp
  - npm install gulp
  - npm install gulp-typescript
deploy:
  provider: npm
  email: npm@smart-coordination.com
  api_key:
    secure: TRT3MB0D0oMNi4Z+dTGLftOxY1yyi+gbcsBRp0WthR48xWVmLUwa6osiIugph+amai+T1xOvqm5+Su89WoWl5YiWr07X/DLEUm382mSpB6HZLyKhwMAn7gWejDG9XdoD1F/NaLNmMmO7NHD0Qv3t/SQJwsrWI6rUEer1QJPr/+AZhEJ8L+YBMT+aW+U1bg7NbHsq7DPChZKU48aF/qq3QE0ioJxxjSw9ri36nutR9Y+5LLFWilJZU2Gx+y/3Y9k3FkWsSX8LMQepCJpspT9GZ+BNf5FzNJFNAtgPU4q7Aj+wOSxp9tVnDogte2UXxQdMfiOz0KywPkYdNrm01ybj9txe5IbBh6dz2pD0BAxtV7+Y05KPDbK0e/j3weG8czni0jkcCAKuBybACP+HP01rmp/FfqN7+90JnPyc0whQxiIcROenGyjHKaDeTDgxdqeX3cpYzkaeSaYkC9D/uDut+pAU6xOOS4IIyTInHhvzMuYedb+XiOJFR0ewhJVdC2eprQyBQmBY7gvjSq7dJwiKaIlN+e6ZlZXbPGSr+F27BdbzNfgXtRNx2roRWcDlwwkotWvslU5zEvJ9rBOX4j6dDAJUkH4LRL7jEne0ev+P+VcgUa77367+D7dXF3QdfISyb+/isYyEM0JGKRMfr2ychj0Bi0SdhonRXYrTuYMRYfc=
  on:
    tags: true
    repo: billtoday/billtoday-npm
notifications:
  slack:
    secure: f5Uss0z9RPl/QcA/DroB8loyE93aOYI6bqCkrsiUscmZtlv/TVQtT4dxqGA6uvcG6iTQDBi3Ul88dQxWkRm4IqbhY35/iMaV2dHW4FVYMAh8GQMbsfL2sALCcufxD9blw47awv3iFcwhV1EeyesscjgL0JIjduk96v/7G/6QIO2838M1lzlgtj+kRUkim8qkaEs1je3gRrhMUIjLuAdscMXyUKYFMjWo9ACSjVUl30R/ZNemb18itIja6i92GotreBgcfEMczvy58ovDC7xdJUsY8LjMI01DwY+WPRnI0tAhsuI8moBwwcdM4e3bAjKjucQRjO33O5bMWRZ6QCiYd0DnCEFyCPQLJ4GSy/tkD00n8ijLHAOSV3AH1zNbdK1EAdSPQXDvlI36KJn/2hyQLoitGHVUPr76ujJWP82ypO2tgIp3XQU0dJVCxDuHnwJO2+hjdI+gCPqxNTpjeujHx3UdkTGNRjuuf9dlZ/D08fApjYxy2fxItTqo3QjP/nrqvBXUOPP8yPHpjIT4H2t5Pr4SJjBGI6X4qhKyFj6s9rA/Xu1rL+45zu1C3uC3z+u3T9UwrbzJ/cZM6r6UQvQmUvIfBNaMlg4I/diQCDIPL+Rhop2nylY3IcHmJnk2itn7kOqj1tohCpFEml5pRuSZy4udWywkdtyBAsHWFLF7oiQ=
